# Generated by Django 3.2.5 on 2022-02-16 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20220216_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default_profile_pic.jpeg', upload_to='profile_pics'),
        ),
    ]
