# Generated by Django 3.2.5 on 2022-03-25 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_alter_watchlist_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='duration',
        ),
    ]
