# Generated by Django 3.2.5 on 2022-03-26 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_alter_listing_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='image',
            field=models.ImageField(blank=True, default='no_image.png', upload_to='listing_pics'),
        ),
    ]
